//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataManager.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountBase_Temp
    {
        public System.Guid Account_ID { get; set; }
        public string Website { get; set; }
        public string Account { get; set; }
        public string Company___EventInfo { get; set; }
        public string Segment { get; set; }
        public string Industry { get; set; }
        public string Industry_Sub_Segment { get; set; }
        public string Revenue_in_millions { get; set; }
        public string Employees { get; set; }
        public string CompanyURL { get; set; }
        public string MailingStreet { get; set; }
        public string MailingCity { get; set; }
        public string Mailing_StateProvince { get; set; }
        public string Mailing_Zip { get; set; }
        public string MailingCountry { get; set; }
        public string Continent { get; set; }
        public string AccountPhone { get; set; }
        public string Current__Event_Name { get; set; }
        public string Current_Event_Fee { get; set; }
        public string Event_Charge { get; set; }
        public string Current_Event_URL { get; set; }
        public string EventType { get; set; }
        public string NumberofEvents { get; set; }
        public string RegProcess { get; set; }
        public string Event_Competitor_Name { get; set; }
        public string Biggest_Event_Type { get; set; }
        public string EventFee { get; set; }
        public string MobileQualified { get; set; }
        public string Categorization { get; set; }
        public string Sourcing { get; set; }
        public string SleepingRooms_RoomNights_for_Event1 { get; set; }
        public string VenueType_1 { get; set; }
        public string VenueName_1 { get; set; }
        public string VenueLocation_1 { get; set; }
        public string Zip_1 { get; set; }
        public string Ever_used_MobileApp_CC { get; set; }
        public string MobileAppOS { get; set; }
        public string MobileAppLink { get; set; }
        public string Developer { get; set; }
        public string EventOccurrence { get; set; }
        public string EventDuration { get; set; }
        public string HaveBreakouts_CC { get; set; }
        public string No_of_Attendees_CC { get; set; }
        public string Sponsors { get; set; }
        public string Exhibitors { get; set; }
        public string Account_Level_description { get; set; }
        public string Company_and_Survey_Info { get; set; }
        public string SurveyName { get; set; }
        public string Types_of_Surveys { get; set; }
        public string SurveyReports { get; set; }
        public string SurveyLink { get; set; }
        public string SurveyCompetitor { get; set; }
        public string Sales_BizDev { get; set; }
        public string Competitor_SurveyLink { get; set; }
        public string Type_of_Surveys { get; set; }
        public string Survey_ReportLink { get; set; }
        public string Competitor_Event_URL { get; set; }
        public string Ever_used_Mobile_App { get; set; }
        public string Event_Name { get; set; }
        public string Event_Type_CC { get; set; }
        public string Event_Fee_CC { get; set; }
        public string MasterVerticals { get; set; }
        public string SubVertical_CT_TM { get; set; }
        public string Vertical_CT_TM { get; set; }
        public string Current_Ticketing_Provider { get; set; }
        public string Sponsors_CT_TM { get; set; }
        public string MobileApp_CT_TM { get; set; }
        public string Competitor_CT { get; set; }
        public string Mkt_CAT { get; set; }
        public string Current_Mobile_Provider { get; set; }
        public string VenueCapacity { get; set; }
        public string OnlinePresence { get; set; }
        public string Total_Service_Revenue { get; set; }
        public string Event_Planning_Registration { get; set; }
        public string VenueSourcing { get; set; }
        public string GroupBooking { get; set; }
        public string ExperientialMarketing { get; set; }
        public string Branding { get; set; }
        public string MobileDevelopment { get; set; }
        public string Social_and_Digital_Marketing { get; set; }
        public string Creative_Development_Services { get; set; }
        public string Parent_CompanyName { get; set; }
        public string Parent_CompanyURL { get; set; }
        public string No_Of_Offices { get; set; }
        public string BigClients { get; set; }
        public string CompetitorUsing { get; set; }
        public string TPP_Score_Value { get; set; }
        public string CompetitorName { get; set; }
        public string New_BDType { get; set; }
        public string New_Chapter_Name { get; set; }
        public string New_Master_Abbv { get; set; }
        public string address_2 { get; set; }
        public string fax { get; set; }
        public string OfficersLink { get; set; }
        public string url { get; set; }
        public string msa { get; set; }
        public string BD_DS_Rep { get; set; }
        public string BD_PS_Rep { get; set; }
        public string BD_Tier { get; set; }
        public string NamedAccount { get; set; }
        public string BD_EMAIL_FILTER { get; set; }
        public string BD_Division { get; set; }
        public string BD_Category { get; set; }
        public string BD_Classification { get; set; }
        public string ParentAccountID { get; set; }
        public string CreatedBy { get; set; }
        public string LastModifiedBy { get; set; }
        public string Status { get; set; }
        public string ApprovedBy { get; set; }
        public string ProjectName { get; set; }
        public string TeamName { get; set; }
        public string LeadSource { get; set; }
        public string Marketing_Project { get; set; }
        public string TaskPOC { get; set; }
        public string Prioritization { get; set; }
        public string SFDCAccountID { get; set; }
        public Nullable<System.DateTime> Event_Start_Date_MM_DD_YYYY { get; set; }
        public Nullable<System.DateTime> Event_End_Date_MM_DD_YYYY { get; set; }
        public Nullable<System.DateTime> EventDate_Venue1 { get; set; }
        public Nullable<int> CurrentEventFee_Max_In_Dollars { get; set; }
        public Nullable<double> Average_TicketPrice_CT_TM { get; set; }
        public Nullable<int> Facebook_Likes { get; set; }
        public Nullable<int> No_of_Attendees { get; set; }
        public Nullable<int> Number_Of_RoomNights_Booked { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
    }
}
