//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataManager.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cventEntities1 : DbContext
    {
        public cventEntities1()
            : base("name=cventEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountBase> AccountBases { get; set; }
        public virtual DbSet<ContactBase> ContactBases { get; set; }
        public virtual DbSet<AccountBase_Temp> AccountBase_Temp { get; set; }
        public virtual DbSet<ContactBase_Temp> ContactBase_Temp { get; set; }
    }
}
